apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hiEmpDWamFCPZtiThBvWlum7bV2NQSTFtzEuGoR8M9FKyC3oTNRK8qDYeHbCigNi9G/je+tPcTMJh0VXeFB5cziewGADo3seMhrrziCDQNCC8Cy+mx+EQicUk4lYT9UIeg23ryHteVhTejdAIj3sxlANsu1orwrOM/90DJGvk3q0GZplJcfR9GcGWeC+RzXU5Duv7YRRki487nz+xI4b+ZmRubR5Slhzvsu8rKJbsoMU6RK73ABMx1O4MomYfNoJ4zxUAEfN8brbc8qWDZrYm7JEvzJ9tfX+NeEHgdvNPsuDhNr+wcRHeDQMVkQkoVNOASBgAnsveShb8FMnHX1AwuPnlyelSQwC9nVtZHOc+KzGIGcxTtADANCmS/E111cd,iv:Y2nA07TJiYP5fJEGeDvsIjod0gQgoZuCn+/uycT9Eyg=,tag:/Puf9NRCxmwM9A1bKI/zzg==,type:str]
    identity.pub: ENC[AES256_GCM,data:JTbefqYrgVx41QimkefJZJQJxa+F/vRxVJmbjj1I8lzv58Y3QRVlZW31hqXcyrhQDIiXvuHJPzQh94zOA1NoxrmYzubjQ9YfCSA/RzEbUWYEVHN2NtuOOw+qlL5a6pcX8bIKwrVJ6svuqshaw29rskyrj02STVG/S86algfe+DTsyvUod2rOlx04jVsaLrImQuIL4lqhL9eGOoUiisjhxL8bWr0bFHozsEs6Aebb/4QDw99D6HzCLpcDk5NsarfIDKt2ImD4+qhKrPwZ0w==,iv:ST/COeBcb3NoqW4yHuBgj58JmELjjj4WBW0FORYSC/s=,tag:85VQfRfII77nhHvAtQ1+vQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:P5HY4HQ9XM3EBWLOIflwnRYAm3GOGYA4m++1eR2bHlw+Wi92FteoeAf0P/SsAU+zISH8NDIhkeyZiBTFsWIpJCssiZPrQ2pHpOdI7MTW22hpEwoSfxicfE9oPu7kntY4mqmq2bL1eeJb0oFM3kgX2C9Kb8vMNI6DtgiOAM7ntkPFNtq+R95J+ayTgUhly9Ac6Ybo1uebFKCL3lr2LJInHK8BEWboQWRV83Pz,iv:QRYhP80HVGmiDX5I4/RV2uM3WtEiUopIloQllDFKUJc=,tag:BYSW6ZCKRr2T3NjvcRtG9g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wqksmfcgcazd8vf4ksh4x0traqfwlqvm3e45eme9uldmhvc3quqqxjqus5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaUgwRzNab0lJUWhNZjBa
            ZWZxSHpTT2ROay9iWEU3czUvclBCdGdHbGljCng5RE40RmNLN25xd1JwcUUxL0ZL
            L25nbDNLU1ErRTdsTjlGdDdKQjlZM0kKLS0tIFNKdlJyWUJIRjIrUnV0WHVHbWNs
            WnRpL2hUWXRmMlFDZTAyUFFXeVphMWMK5WSs7OoeoDkevv7otewZp19LFcv4DwmO
            oKFrM7zcbehRplv76RX4I/fsijLr+pXJqkuJAyJWIK8txxTAYS7qjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T13:32:11Z"
    mac: ENC[AES256_GCM,data:o97cjcUnZSDEO0754tcZ+avZw7WY9rfbsnfZyXmw2Lxogm/WzVeWrds+GG6e6F8simbIUBA1G//4agNpbdwDYdWr6c3OfkmVF+GS5qJaNG1sJZ+F2x2CHPB4PYRPQRtuo+sVPf2tx4UhBpLILs88pnecylHubzn8ZUrYU8A5DyQ=,iv:fo9on40Ev1341x0hLJ/B9Pg1WlT5Ed0nv+Xd9ulZpWY=,tag:8G2pj3JNe61YMtk2jI1yiw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
