apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FjIcTBMxnWUU6t4yDYDoC15auBLBnJc0fqFLvCx1w2NIJoIuJ/UzB3SeG7FIIgC8r0CAcF0CV42LM9XZO8ShMXUf2tD1Ox+fYoGLvFA12aZQC575/pYIcQMnUjLBVGzXj7A8LvIATDRwbV26AHRt1weDEypF5VvmK9IcGtb8eJZ9Gt8mgkMfb8x2b8rlSzrvvIPgM3xGD67aEB4YhDJ915hyobblP8ZwomuRqqqOTnwq4GodeoJpk1XEm1NTT3lM9iNngYKgmxBmZDhhEQmesFPzfdyefd8etj1JVyTZlMselmDgV/VRqS/WX55XL3pzCVx3kcTdFqxidsiIHfr/LPs62CvhGgiVggh7TEm7LI6ajH9TB2gu1GAWTfdf/Nme,iv:Y352UQDcaQwdOY2b+qt5EfPSXnJHxEFx+DoSfNLfa4I=,tag:OZc6N1kE01rr+cl4hnB3fw==,type:str]
    identity.pub: ENC[AES256_GCM,data:6DtlCe/vlL2SRjrd8W/P6OJOsjcHZ79tYjzdhhu00htyMJaSEUEI5ruDL61mxYzR0W6Ma5rcJDtx3NxLMouU9HY5KPmsWzHwelZO2N8WeRgdMyB/26bSIiZHkcxzMGbin2Jzue6D8nQPwIP3tGXRHxjAvc/WDHySX4Q97aitujooEwLcTtLfcO5u5mTkEg5SEwFGYss65pcEk+DshS8dt97NqVgrt9/YSbLIFZhbXncTUi9vihp6HS99phXKxTqWJ2v888IXUV6i9mhvEA==,iv:vkZ2itDIZ3fst/rRvVxdd9Dba12bB/NbeOIMF2NW5wE=,tag:zHObAka93z/eW5cz0dWK+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:6aRpDMEnrhMqABF78xjazyLqRTonHG83a4ZVQjsox//MU3cfyIoIk5hP23wQROF2nYMuUK3hxl7CDXaoRE9cz+Vu+9F7djwVv3KwGHw2k4cyVQl0Qb5oEWa0G28cINnk3LLDg79u6i7ZC+f3fzb7Q76q9WDmyBZT2wQKi2OsSnhSc9ifpx7+H/LjzsyHLoRlHu/3RW2zh7DZp7XRUK8EFQxy+WpxKt6zRHME,iv:H+a3NPXYel8IyA5a/HsL5l5nGxTuPbJT/PYQ7vV2Zpk=,tag:e1m63UOd4v4SD0sXFVRKlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wqksmfcgcazd8vf4ksh4x0traqfwlqvm3e45eme9uldmhvc3quqqxjqus5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSG9GcE5maFdaK1YrcVo4
            MUdrSDR2Z1JKT2RXMHNvR3hqQnRhTTFlc21JCjJqRjU1RlB4WWpFTTlyZVh4cFFL
            Yk4yQW9xczJVaGpDeFlGcEE3d0xDSWsKLS0tIHFoUkpGN0Vhc1RHRVFkYUJTc1d6
            T0h2OURId3hpQlA0Z3N3ZW1xR0VWdlEKdZhjCchmEfllDUete3zsQmALZsUU2PoQ
            GMTd80wQNTC5Y/4uwrJ70NtH4fMpktdRhGTyiZ2CIhZ8hFKxTc92Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T12:10:03Z"
    mac: ENC[AES256_GCM,data:RROSIKmH+IAjv/4Ssf8MBBM4sApjtkfBX9iP/f1OEB8M5hhfbOq5ZWr0B02BBl/+s8jTR5B04LKbaZPz3AogpXwGWBMNDHQfk649E9npt2R4+DAtS06RpRcjLhpeGrHmNS77yTrdhedfsqVcks38AVybopge+8EruDBVIG+9ioI=,iv:7VqVEDHjRaDpoa0DHD0IHxf+h+B2iejM9wraPao1Lic=,tag:gWUPjQbTx84fxLJ5NzNoew==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
