apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H+zH36vDI9TlopDFBO2QRxvsiYQPhQzQ+dKaTwYZkGCf2ixQhd1OYzE3L46zRzvcFbXy3aIbCNh5/c0+Ch+M8DJU1q7dGszHTzQD5VLPT5DC4UhCJhsnTFCfaK90xoj2Kwdv31Bgw7s9Nodv0j4itbFi99TxYYHd5WY72bh5oJSbY+njZPLQ4oImCprhFNXTMrpfChY8DFQ+u2e+dzxWyiqM2hrOVVlLQzlBOqgHESAANC/RHkwnDTLYrfPpV+qThl1ZeKqJejZIT8cgv++3KFHQ/VieDBRvlYoSl88vCluFt74FD97xB6dwev6lbL7wl9i7jkhdDH7twSUof44RN7qoqlPkPdhj5ZBC0icE143ScubpEZkEqX0stGWjWZfl,iv:vJ+2v02lJlNDVE1hppG4MmsBOYtDt0vzocNRd1QDzw8=,tag:QaDphk6P6TN4BmEiPMPwxw==,type:str]
    identity.pub: ENC[AES256_GCM,data:E26ZT2bri8nBFfByenOxcIFkrdnzU3MGL1DfiX1b01bKh/7IsrJNtMqinSqY9Rw4s3OC4ZEkrmvPG7pBX2sY1r3vgla2Zmu8XixjeAKWh+zrMx1B0mVORUWXY77SIs9TgjmK3ujdKWiQIEhbJMYKFf4vptcMjndVkwPK7iUOjY/OrmfKgX44fBYrSULndMXG+bFuw05cnnq0VizA68x+lI2Z9MXtkZO4B8hgm2coQcBemyVM5ph8c0wLo+MZMP3d2CHvKbfD9XVh/mHg1w==,iv:fSTGE2jPUvPzqLT9m+eXsAgjxtIA3wyNiE2KBZtdBmE=,tag:DZGXuN/D6VHh/SKQnTGNrg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Yo9jwqAWaaeXlk7QeadmAmbs1sEHy5KbNhvg+q0OSW0Aa1NGAgD0pnpZtXRmf/5tyKvMxSdifss974waS+3+04RLqQJfyIKysHEWDEceqEu2DWuBJggtEqz63MAjkEEuUUn42sVmmElxkzOE3lC+C4eP0yBHtYGV1KGyd5fjWJmeqBS5w14SaOq6Wyw8tRSegRtqKXkOuohKHm6V2g1cRGtcScQO0AnF4X8R,iv:ePWbpGWMvn8l/y75oteH+b2aAWcAvYTDIzSqwFaz684=,tag:ycGxnWG9I4tmHeapBTRCjQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wqksmfcgcazd8vf4ksh4x0traqfwlqvm3e45eme9uldmhvc3quqqxjqus5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTjg2Y2xhYkFzZlpJYjd4
            MHVkaVlHRXB1UmMxSG5JR1MyZm52bWdCV0VJCmZ3bW5reE42MmwzQ25QQ3lLMnF4
            WG4walJYSzMzRzMydDdmRzdHWmE4d0EKLS0tIHdLQ1hHdE5qaC9VdVNWM2FXdHl4
            VkVDTnNkYzJzcEZ6eVVtcUp4OUFVQTgKiW/ZNqiH6JiT7AlRYhUfD5CU5WK5Bsxs
            nhVuZNGuWH+aL53PkmMVTXSxuxWm1IHurlDi3qTaJr+1rcaHvK5j3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T11:26:27Z"
    mac: ENC[AES256_GCM,data:8ntiRWzfqVvGoFcXAF/Ng6kaweSsyCtVIc90DmWMbpVLJHp1ajuItSTTf3KEElRy7CXKyZ9dK5yK/PMtYjnDi4G4iJRchpGR7RK/NKReCT5m7UrcKO5iIjZOoKspuBoTsKc788AlRn+NR5B3EQJB532zQS5ekwaqCAEbb/x2TjA=,iv:6PRTW19d5fxMlckup97ox/UD2zrHN/sBtalKuPIhKYI=,tag:yLrGIPAfeOZiW4Xg+GV3Rg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
