apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HWXPLhoIqGL3Mn/MLw0EQgbtdYF0pjqvKwNhiQDWtUghn3qpE8On8T8s/hsgqINbFnKnJttyy8q8T7wVj55eJDjoHkMZQ/1sY6T5sp+EtXbYwYoi7eJPb0DvzkyijOozNUkS0NZHIDuUDtGNv7tHbQZysw52eSjvsGR+LrIBtuOaERFm3FnwZ5StZwpT0brA42ZNOZBWdy8BhVpNEN+03WdJw72VYCsIWgMPcOqQ0IQU7GsDs1KKogjStErp+5S0MlVWhDY3g8GBqZu+bqXrcZED7fQIa4rqu9Y9xl81NNt77mw4/5F34JgNeXdRvJG53uyhf7+Z4lhRXZJC0ZZC+0eGW+7U132X5elSJ2KKCzusmvbhY8tHrpLD8d2QcV9y,iv:dsr/fI3H7dnpamnOOrhUeuRaFex5TqcPbmslyEF835k=,tag:Bh2SJmQ4yraUHnQUU7z22w==,type:str]
    identity.pub: ENC[AES256_GCM,data:1YCW78cP5KRkZE8FmOVshBtvENVgMFjeSfxA7KgHfOBMv5H3m1Gll26oo8PSduiGXyTb2DvWpvGNzJ8Z0HQ25GmN/wYXphOaVAzchYJt0IR9L/4VDXEDM9aQLF8A9ySysHb/35TqsApH62U9ZFxregbGfqHiaJ9NHXYyB9V0XroBSUG6qO/TOKC80hS/Okc5EOFosNSjDW1sqXYoGPa4wqLfo0vmaK4ygZ7euID1HsdAESEBP7ASJR9AMeaQIICmni4eCCS26h9byhirxw==,iv:n/CYqvxEkDDpYCJglj2tQ0DLcNUE0o9MAf1N5durKsc=,tag:bIahwrQaJBUmDdgnEXt1qg==,type:str]
    known_hosts: ENC[AES256_GCM,data:tepPlHRgxtxA9tJxJkY2ih2/gzvmDM3SaDp2+GwNRQQtN+D+1PirK4iqio/5dWOlidUaqcrjPl7Q/tKOIEkbpl+9N10/JXiYHnp1pGAHcmoxx9a/xcrFAmbe7kt/Ro6OaaJZWLlwYDTOeg73D6a/N4Y10Vc9BHjLXMy9T2KZPoyoU8bQ4neJdGU5xp+eMqWOH2jueNRt5kvncsrbkmq4xpPJaWSMQ4uiG+lr,iv:1sYGsknYhmeQ0i6kmqERrTci2xi1MVAWYHPB1MDFeoM=,tag:YOFulfQwtXrO4fHg3aZWWg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wqksmfcgcazd8vf4ksh4x0traqfwlqvm3e45eme9uldmhvc3quqqxjqus5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM3kySlZvVnVUekF4Q2Vu
            NXN4QmlHVm9zYXFWd2RrdGU1Sm5vaUVvMEZnCjd4TUgrT1hJTGQ5bVFveG94bW5n
            aTRRSDVEODh3WVozL1Izd3R0SFRyME0KLS0tIGtEemRiQXJ0enhJczVnQVpjN1RD
            MzAydkxBN3R3NmtRdVZBU0kzMXVlVTQKrslA1kJoVoyImBeDdFJsUUwUYJcu9vU9
            7uuj0ARX8cs8dPJx1pGOQBfapLpXhxCyHlWcDwHRhj/XbHdZSuJRVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T03:32:53Z"
    mac: ENC[AES256_GCM,data:lwIfLuWMgLGZEXWehfIGbOab8MJYFr9KANt8BgFDK/wSfYy9GtbrSpdySX8rXtPQBp3OIBeD2nmryw2xc+xDSUT2WEB1FdzLqaTbXyTtTbiJncVI7LI2F6rHkfuLRLuU6alnmdtaBpA4DV3RBnH/tJcZaesNaqGj9vPbaLxzBgg=,iv:ouf5Ook2JmtQibBVHuXc/TsXi0Z6og1GgVyDYWb0r4g=,tag:TAg0XIgjWA1lgGjo8/NFNw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
