apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UIev50HWVLFJLWglYeCxR1SuGxH1Pz62/xqr6eIECzCzj4tytDByvpx5FPeevQLkTJQ6z3z6ZfhstjEjTgLEVmRhxswO9FSv9rbCxOuQWXqpGGVKTRo3gu11c7emTu3UodwMcfviW2Q9izeJkvzIDvtJllrbQIfDw/769Ggas/5YSim9UAZov5/VyesjWluAHgSAorHVJWXYCy3sRFdkPHvuds4jZGeiuqqa08eZS0QFr1UvS1POSo4Y2b9W2/+UaTNcnNtJVk5/+z1bh/2HMi/tL5g4fx0Jvoq3pF0xlBuWtQaw0oj/Hu9PzFTptB2fbn+wMKpZK2wSGMMQDiQJnZKJBdvwLaugOm6H0WuG0jDcNbhZwh2TUXi0OWi+pJ12,iv:Gw1/UVhFjZmgWfn+oso2BGZSpx8l3GVwKgiIsz8iUoE=,tag:ZFOa/tRwojb8/hBiKvFDmw==,type:str]
    identity.pub: ENC[AES256_GCM,data:99sf5orb8OC76TlQEU3f1T/M5CRyJhmp6YfdnkETfjB8IfxIFRw5gQBfoNqYp/J2EgVqCmAxcvgVBuROc/FffRLN1O9S6Cm7RsfxqjPLJZPQJ7L8k4xZDF9nUfbP/NhchJGcVqki7PJ3I6pGgZk2h47nqyzhjVmbjG+C8ZwD/IKI2JZTvrV3c7F9cdAeH779cO1hRg65vp45lTjp/ucNy+4+NSI7G0pDakitgdpwvzT/t1OGdXtEUG1F8g57fIHje9dlEj+/29vDYnFkSw==,iv:1BiO6PcoaCQzK5Go5VfyJebe/3qUKNLIa4pMrp3WswY=,tag:AxmyJyxSwNQ4N9zREsifMg==,type:str]
    known_hosts: ENC[AES256_GCM,data:+FtrF4pVfc2yJy1Jhgd3RxxAEreqZ1CJltbCbEYuOpHxgqKILdIJGl/PSR/RS2mHxQukwuqo8z72iTKEEf0KPf/WlKCQvDahRBIGrT6V/HEbOrhyVvdRHgFKxU4YwPbVwnzmeyLERQv9Ui7/RZ87ZooD4VGU5oHGWLTjXxRrBtgthR6r9Ube3gciJzrD9AyJLz2unh2UdgRRjQ2imTQAyT5/gPFEezDmhgbj,iv:bTS5B1JipC/cKQ81+ME+HTbog56d+sOV1E98ELSXLWs=,tag:JVYKuwdB+4VWrheYBbL3Ew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wqksmfcgcazd8vf4ksh4x0traqfwlqvm3e45eme9uldmhvc3quqqxjqus5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWkpKeGVpNU9ONVo3N2ov
            WjFRKzZkNnl3TVdydWFZNWJmdmNWQWZzV1VJCjNBSWdjRURPaitabXJtRjlOeDd0
            UHFIYVlCdmlGenQ5M2IzUGJZemZha0UKLS0tIFdmaDczUW4wMktqbFVMWkV3SjJq
            NTFwWmNpcE9ONVBPcC9OeG9WQ28xczQKh5vzqnVMMA6O4ypdedbg+5OYRxu7JDFC
            b4VEfquTHOFHJtqXncLZsa2bpPXmRrPe6cKyFPfegbfE360L+8Hh5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T13:16:46Z"
    mac: ENC[AES256_GCM,data:wqKzCBiFq3f/D02+2cYU9kgcMnLjE+9182+1OKur+KQMdFQ3DedEusvf9cuq2PVc7P8ssqawNgmyoGUE+zjOOF/yuK6ruY6/q4p6aExmXBQWVyYQBddcswO1H7Hv/YH3bRbmCpeDwD1qF8/jLYr8it/J8XbNqe10e3QdotbiQfc=,iv:qotC7YYbE9Wm5rkFTuxDkvqpXkk71R7FxANx3uBU9PY=,tag:NVwKw0DvXfgqSD/9Lk/Dgw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
